--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skyss0fly-pm-pl/VegaLeaderboards
build-by-default: true
branches:
- main
projects:
  VegaLeaderboards:
    path: ""
    icon: "logo.png"
...
